### ISSUE TITLE
Problems pasting bullet list

### ISSUE THREAD

**Issue by michael-milette** [jinhofer/pastespecial#6] opened 2015-11-06 14:52 UTC
Hi Joseph,

The plugin, version 2015082600, seems to work well in Moodle 3.0 RC1 however I don't seem to be able to paste anything from word that contains a bullet list (List Paragraph style). I am pasting from Word 2007 into Chrome. I seem to only get the last line of the bullet list.

Haven't tried it on previous versions of Moodle.

Best regards,

Michael

**Comment by jinhofer** [comment] 2015-11-13 14:29
Michael,

Thank you for pointing this out! It appears to be an issues even with pastespecial version 2015101900 and Word 2010, due to the way I am handling inline comments. I'll get to work on this and have an updated version for you shortly.

**Comment by jinhofer** [comment] 2015-11-13 16:26
Michael,

I have fixed this functionality in version 2015111300. I'm going to close this ticket, but if the issue persists or you have a new issue, please feel free to create/reopen a ticket!

**Comment by michael-milette** [comment] 2015-11-13 19:20
Hi Joseph,

Much better!

However I noticed that it is adding some paragraph tags. Here is what it looks like in Word with Show/Hide turned on so you can see exactly what the formatting is:

![image](https://cloud.githubusercontent.com/assets/3808579/11155014/c8420500-8a10-11e5-92e2-a83700c694b8.png)

This is what I get after using PasteSpecial with the Microsoft Word option:

    <h1>Atto</h1>
    <ul><li>Accessible</li><p></p>
    <li>Fully integrated into Moodle</li><p></p>
    <li>Simple but expandable</li><p></p>
    <li>Leverages browser capabilities</li><p></p>
    <li>Mathematics support</li></ul><p></p>
    <p><br>&nbsp;</p><p><br></p>

Let me know if you have any questions.

Best regards,

Michael

**Comment by jinhofer** [comment] 2015-11-13 19:36
Ah, that's because there was a straggling </p> tag that I forgot to remove. I have accounted for this, thank you!

**Comment by michael-milette** [comment] 2015-11-13 19:50
I just downloaded the latest code from GitHub. Now it doesn't paste anything at all. Is the fixed version on GitHub?

Michael

**Comment by jinhofer** [comment] 2015-11-13 20:05
Hmm, I'm using the latest code from master branch on GitHub. Try clearing the caches?

**Comment by michael-milette** [comment] 2015-11-13 20:21
I deleted the old files and copied in the new. I Purged the Moodle cache, Reset the PHP OpCache and cleared my browser's cache. Still doesn't paste anything. I also increased the version number in version.php to 2015111301 to cause Moodle to consider it an update and went through the whole notifications/update the database process.

It still doesn't paste anything at all.

**Comment by michael-milette** [comment] 2015-11-13 20:23
If I paste plain text, it works. But not my sample content from the Word document.

**Comment by michael-milette** [comment] 2015-11-13 20:26
I just checked in the Chrome console and notice that there is a javascript error:

Uncaught RangeError: Invalid string length in this line:

    text = this._cleanWord(front + '<ol>' + '<li>' + mid + '</li>' + end);

**Comment by jinhofer** [comment] 2015-11-13 20:28
I am definitely not seeing that error, but that would explain why nothing is being pasted. What are you trying to paste?

**Comment by michael-milette** [comment] 2015-11-13 20:43
The same thing. See image from MS Word above.

**Comment by jinhofer** [comment] 2015-11-13 21:04
So I'm pasting this:
![image](https://cloud.githubusercontent.com/assets/8837519/11157464/2c600040-8a17-11e5-9d8d-a81d07eada60.png)
into here:
![image](https://cloud.githubusercontent.com/assets/8837519/11157474/3caad3d0-8a17-11e5-9dd8-623dc0df3eb0.png)
And getting this:
![image](https://cloud.githubusercontent.com/assets/8837519/11157487/465099ce-8a17-11e5-8543-64708abfb4b8.png)

Looking into RangeErrors, it seems to be with the browser sometimes. What version of Chrome are you using?

**Comment by michael-milette** [comment] 2015-11-13 21:06
Here is the sample document I am using:

[2015-11-13-pastespecial.docx](https://github.com/jinhofer/pastespecial/files/34353/2015-11-13-pastespecial.docx)

Open the document, press ctrl-a to select all, ctrl-c to copy and then go paste it in the pastespecial plugin using the Microsoft Word option. 

You will see the text in the dialogue box (though the bullets will not appear) and then click the Paste button. 

I am pasting into the content areas of a Moodle 2.7.11 Page activity. I am using Chrome version "46.0.2490.86 m" on Windows 7.

Best regards,

Michael

**Comment by jinhofer** [comment] 2015-11-13 21:09
Oh, it's Moodle 2.7? I'm having success in 3.0, but I will try it in 2.7.

**Comment by michael-milette** [comment] 2015-11-13 21:12
I put a breakpoint just before it executed the "text = this._cleanWord(front + '<ol>' + '<li>' + mid + '</li>' + end);" line. All three "front", "mid" and "end" have a value. "this" is defined and I can step into it. As I single stepped through it, I noticed that _cleanWord() seems to be calling itself recursively. I went through the recursive loop a few times but, without knowing how long it was going to keep this up, I gave up before the error occurred.

**Comment by jinhofer** [comment] 2015-11-13 21:14
That is what I'm worried about. I intended for it to be recursive, but I fear that the error is arising because it doesn't like how I made it recursive.

**Comment by michael-milette** [comment] 2015-11-13 21:16
But it was working better before you implemented the fixes to get rid of the paragraph tags.

**Comment by jinhofer** [comment] 2015-11-13 21:18
That's the confusing part... All I did was change 11 to 16 in one spot in the code.

**Comment by jinhofer** [comment] 2015-11-13 21:26
Okay, so I was able to reproduce the issue in my 3.0 instance after some research. It's because the function is recursive and occupies too much space. The error thrown varies depending on the browser being used, and some servers have more space available. I think it'd be best to make that a for each loop instead of a recursive loop (unfortunately). I'll keep you posted.

**Comment by michael-milette** [comment] 2015-11-13 21:29
Thanks. I just tried it with my 3.0 RC2 and it does the same thing using the sample word document I attached earlier. Weird though. It's not like it is a huge or complex document.

I will keep an eye out for your update. Sorry to be such a bother but I really do appreciate your efforts, time and commitment.

You'll never see this kind of response from Microsoft or Apple, no matter how much you paid for the software. Thank you Joseph.

**Comment by jinhofer** [comment] 2015-11-13 22:26
Michael,

I have posted a new commit to github that I have been able to successfully test on my instance. I handle the issue by first counting the expected number of loops, then executing that many loops. Can you test the latest version from github to confirm it works before I publish it?

**Comment by michael-milette** [comment] 2015-11-13 22:55
Sorry, just noticed your message. Give me a few minutes.

**Comment by michael-milette** [comment] 2015-11-13 23:02
Results from Moodle 3.0 RC2:

![image](https://cloud.githubusercontent.com/assets/3808579/11159775/bbd8e14c-8a30-11e5-92ab-93858f709450.png)

**Comment by michael-milette** [comment] 2015-11-13 23:06
Same results in Moodle 2.7.11:

![image](https://cloud.githubusercontent.com/assets/3808579/11159839/45394788-8a31-11e5-9f89-29e27832dc9e.png)

**Comment by jinhofer** [comment] 2015-11-13 23:34
This sure is frustrating...
Can you paste the text into the pastespecial dialogue as normal, but instead of submitting take you take a screenshot of the HTML and send that to me? Mine looks like this:
![image](https://cloud.githubusercontent.com/assets/8837519/11160242/cfa09836-8a2c-11e5-89b6-39f823958e65.png)

I'm going to have to leave in about 30 minutes, but be assured that I'm not done with this yet.

**Comment by michael-milette** [comment] 2015-11-14 02:45
Here you go...

![image](https://cloud.githubusercontent.com/assets/3808579/11161616/be057e16-8a4f-11e5-9648-16a6b4355efa.png)

Let me know if you need anything else.

**Comment by michael-milette** [comment] 2015-11-14 02:53
Here you go... from Moodle 2.7.11+:

![image](https://cloud.githubusercontent.com/assets/3808579/11161646/9dceea14-8a50-11e5-83e8-3abdb1a6f12b.png)

Looks similar but not exactly the same. My default language is en-ca which is probably why those span lang="EN-CA" tags don't show up for me. Let me know if you need anything else.

**Comment by michael-milette** [comment] 2015-11-17 01:42
Any news?

**Comment by jinhofer** [comment] 2015-11-17 02:11
Sorry, I'm just seeing this now. I'm a bit concerned about how your HTML looks fine to me, but it's clearly being pulled incorrectly. Would I be able to add some console.log lines to a separate branch and have you send me the output?

**Comment by jinhofer** [comment] 2015-11-17 02:27
If you could pull from the branch Wordlist and try to paste using that, then send me the second occurrence of the console.log. I've added console.log for the text, everything before the <li>, the content within the <li>, and everything after the </li>. I'm thinking that somewhere in there is h1> getting repeated. It's also concerning that everything is getting repeated, but that will have to wait until after cleaning out the h1>.

**Comment by michael-milette** [comment] 2015-11-17 03:33
Hope this helps:

![image](https://cloud.githubusercontent.com/assets/3808579/11202039/e2719c1c-8cb1-11e5-8976-c61d11a996ec.png)

That's all that showed up in the console.

(test conducted on Moodle 2.7.11)

**Comment by jinhofer** [comment] 2015-11-17 03:47
I think I see something. I was able to reproduce it, and I think I might know why I couldn't earlier.

**Comment by jinhofer** [comment] 2015-11-17 03:51
Alright, could you pull from the same branch and test again? No need to check to logs, just test it against your code and let me know whether or not it works.

**Comment by michael-milette** [comment] 2015-11-17 14:29
MUCH BETTER!!! :-)

After I pasted, it actually looked exactly like I would have expected. Thank you so much! Onto the next challenge. 

Using the same Word document, I doubled the same content within the document. Then I pasted it in using this latest version of the plugin. As expected, it all appeared correctly except that the second list ended up being an ordered (numbered) list instead of unordered (bullet) list as it is in the Word document.

![image](https://cloud.githubusercontent.com/assets/3808579/11213932/b66e7fa8-8d0c-11e5-98e9-92ea68582470.png)

Here is the new sample document which includes the 2 lists:

[2015-11-17-pastespecial.docx](https://github.com/jinhofer/pastespecial/files/36760/2015-11-17-pastespecial.docx)

You're almost there Joseph !

Best regards,

Michael

**Comment by jinhofer** [comment] 2015-11-18 13:49
Huh, when I paste that document, I get two sets of bullets. Could you show me the HTML of one of the bullet points? I want to see what the style is on the span, such as here:
![image](https://cloud.githubusercontent.com/assets/8837519/11242668/d2d9e4e0-8dc8-11e5-945c-7fee61c296d7.png)

**Comment by michael-milette** [comment] 2015-11-18 14:22
Not much to see. It just uses OLs instead of ULs for all subsequent lists after the first.:

    <h1>Atto</h1>
    <ul><li>Accessible</li>
    <li>Fully integrated into Moodle</li>
    <li>Simple but expandable</li>
    <li>Leverages browser capabilities</li>
    <li>Mathematics support</li></ul>
    <h1>Atto</h1>
    <ol><li>Accessible</li>
    <li>Fully integrated into Moodle</li>
    <li>Simple but expandable</li>
    <li>Leverages browser capabilities</li>
    <li>Mathematics support</li></ol>
    <p><br>&nbsp;</p>

**Comment by michael-milette** [comment] 2015-11-18 14:29
Sorry, I think this is what you wanted:

![image](https://cloud.githubusercontent.com/assets/3808579/11243586/df1ac4fa-8dd6-11e5-99e7-b43484597e0d.png)

**Comment by jinhofer** [comment] 2015-11-18 14:32
Is that the first instance of "Accessible" or the second instance?

**Comment by michael-milette** [comment] 2015-11-18 14:35
The second.

**Comment by jinhofer** [comment] 2015-11-18 14:41
Do you mind if I add a few alert(); lines and have you tell me what it's telling you?

**Comment by michael-milette** [comment] 2015-11-18 16:24
The alerts didn't make a difference in Chrome however it did in Firefox. As it produced almost 200,000 lines of HTML, I am attaching it here:

[2017-11-18-paste-special-alert.txt](https://github.com/jinhofer/pastespecial/files/38066/2017-11-18-paste-special-alert.txt)

Just rename it with an .html extension and open in your web browser.

**Comment by jinhofer** [comment] 2015-11-18 16:43
Oh, I hadn't actually added the alerts. Yikes, that's some nasty HTML.

I've consolidated my work so far into the master branch because I did a bit of work on a different topic. Can you pull from master and try again?

**Comment by jinhofer** [comment] 2015-11-18 16:44
By the way, I'm opening this issue again since we're finding good issues.

**Comment by michael-milette** [comment] 2015-11-18 17:10
I tried it again with the master branch.

In Chrome I get the same results, with bullets for the first section and a numbered list for the second.

In Firefox, well, lets just say it's been about 10 minutes and it's still working on it after I clicked the paste button.

**Comment by michael-milette** [comment] 2015-11-18 17:11
I ended up closing Firefox as it became completely unresponsive.

**Comment by jinhofer** [comment] 2015-11-18 19:09
Firefox should be fixed now. I still can't reproduce the issue with respect to the bullet points, though...

**Comment by jinhofer** [comment] 2015-11-18 19:14
I'm put some console.log steps into the Wordlist branch. They will tell you whether it's opening, closing, or adding a list item and tell you which type. Optimally, it should look like this:
![image](https://cloud.githubusercontent.com/assets/8837519/11251295/47631f16-8df6-11e5-97a4-0edcdb5423df.png)
Let me know what yours shows.

**Comment by michael-milette** [comment] 2015-11-19 06:18
I tried both the master branch and the Wordlist branch in Firefox. The Firefox issue remains the same as described above. I am using Firefox 41.0.2. I just updated to Firefox 42.0. The problem persists.

**Comment by michael-milette** [comment] 2015-11-19 06:39
Using the Wordlist branch, this is what I see in the console:

![image](https://cloud.githubusercontent.com/assets/3808579/11264022/52ee1f44-8e5e-11e5-9a9d-b046e1cc4df7.png)

**Comment by michael-milette** [comment] 2015-11-19 06:55
Tried it in both Moodle 2.7.11+ and 3.0 (not RC2 anymore). Same thing happens, first list is bullets, second list ends up numbers instead of bullets.

**Comment by jinhofer** [comment] 2015-11-23 18:27
Huh, that's very strange. Since I can't yet reproduce it, I have a last resort. Since you seem fairly savvy with the web inspector, I am comfortable asking this of you. Could you please paste the content into the pastespecial plugin, but not press submit? Instead, can you copy this div and everything inside:
<div id="_atto_pastespecial_iframe" class="atto_pastespecial_iframe" contenteditable="true" style="width:100%;height:200px;overflow-y:scroll;border: 1px solid grey">...</div>

and send it to me as a .txt file. This should make me able to perfectly reproduce the issue.

**Comment by michael-milette** [comment] 2015-11-23 18:50
Hi Joseph,

Here you go. I am attaching both the HTML from Chrome as well as Firefox. The version from Firefox seems to offer information that isn't in the code I got from Chrome:

[2015-11-23-pastespecial-Chrome.txt](https://github.com/jinhofer/pastespecial/files/41905/2015-11-23-pastespecial-Chrome.txt)

[2015-11-23-pastespecial-Firefox.txt](https://github.com/jinhofer/pastespecial/files/41906/2015-11-23-pastespecial-Firefox.txt)

Hope this helps.

Best regards,

Michael

**Comment by jinhofer** [comment] 2015-11-23 18:58
I'll be darned, I was able to reproduce it! This is perfect, and I can work from here. Thank you, I'll keep you updated.

**Comment by michael-milette** [comment] 2015-11-23 19:02
Thank you for not giving up Joseph. I really appreciate your efforts and commitment to resolving this issue.

**Comment by jinhofer** [comment] 2015-11-23 19:04
So I'm going to keep working on this, but try changing the items in the second list and paste both lists.

**Comment by jinhofer** [comment] 2015-11-23 19:20
Alright, using the code you provided I have been able to find the source of the issue. It was due to the fact that the bullets were identical, so it was finding the first occurrence of the string (the first bullet) and comparing that instead of the <span> that I wanted. That being said, I have improved upon that comparison, so you can pull from master and should have no issues with pasting duplicate lists.

**Comment by michael-milette** [comment] 2015-11-23 19:20
Here is a new twist for you:

If the lists are identical, the problem shows up.

![image](https://cloud.githubusercontent.com/assets/3808579/11346791/4ffadd90-91ec-11e5-96d1-4c156f000bab.png)

If the heading are different, but the lists are identical, the problem still shows up:

![image](https://cloud.githubusercontent.com/assets/3808579/11346813/847f753a-91ec-11e5-8cd9-a940a7214085.png)

However, if the first item in both lists are different, the problem goes away:

![image](https://cloud.githubusercontent.com/assets/3808579/11346875/da511810-91ec-11e5-870b-e985ae59297b.png)

If the first items in the list are identical, it doesn't matter what the rest of the list contains, the problem will remain.

Do you still want the HTML? If so, let me know for which scenario.

**Comment by michael-milette** [comment] 2015-11-23 19:24
Sorry, forgot the last screenshot:

![image](https://cloud.githubusercontent.com/assets/3808579/11347095/e5c9e1e4-91ed-11e5-9dad-3c00379330a8.png)

**Comment by michael-milette** [comment] 2015-11-23 19:31
Here is a new Word document with the content for this last test:

[2015-11-23-pastespecial.docx](https://github.com/jinhofer/pastespecial/files/41954/2015-11-23-pastespecial.docx)

**Comment by michael-milette** [comment] 2015-11-23 19:34
Sorry, just noticed your message. Will try right away and get back to you.

**Comment by michael-milette** [comment] 2015-11-23 19:47
Beauty! It works in both Chrome and Firefox :-)

![image](https://cloud.githubusercontent.com/assets/3808579/11347613/49b4d2d4-91f0-11e5-93bf-68c3c0740981.png)

Again, thank you so much. This is wonderful ! ! !

That's all I have for you right now but I will be sure to let you know if I come across any other issues.

Any idea when you will be releasing this latest version on Moodle.org/plugins?

Best regards,

Michael

**Comment by jinhofer** [comment] 2015-11-23 19:50
Michael,

I should be updating it soon. I'm currently working on another ticket as well dealing with Microsoft Word, and I'll release them all once I have a good version. I'll keep you posted!

**Comment by michael-milette** [comment] 2015-11-23 20:03
Thanks Joseph! Looking forward to it.

**Comment by jinhofer** [comment] 2015-12-03 16:23
I have released a new version to Moodle! I'm going to close this ticket for now, but please keep me posted if you find any more issues.

**Closed by jinhofer** 2015-12-03 16:23 UTC

**Comment by michael-milette** [comment] 2015-12-03 16:28
Thank you Joseph. So far it's looking good. Thanks again for all your work and sticking with me through all the debugging.
