### ISSUE TITLE
Problem pasting text with internal links or footnotes

### ISSUE THREAD

**Issue by monnardj** [jinhofer/pastespecial#4] opened 2015-10-22 07:10 UTC
If the text to be copied contains Word internal links or footnotes, it is truncated in Moodle. For an internal link, the text starts just after the link, and in case of a footnote, it includes only the footnote's text (see below). Selecting "Paste from Microsoft Word" or "Paste as unformatted text" doesn't seem to make a difference.
![text1](https://cloud.githubusercontent.com/assets/5880250/10658953/2014c3d4-789c-11e5-87f1-58abf5d03ba1.png)
![text2](https://cloud.githubusercontent.com/assets/5880250/10658958/2bbc556c-789c-11e5-9bd6-1ff7259cb99f.png)
![text3](https://cloud.githubusercontent.com/assets/5880250/10658961/30d48c22-789c-11e5-9f57-d82c05c8f93e.png)

This was tested on Firefox 41.0.2/Yosemite, Moodle 2.7.1, Word 2011 and 2016, and version 2015082600 of Paste special.

**Comment by jinhofer** [comment] 2015-11-13 16:22
I have been able to recreate this, but since Atto is not currently capable of utilizing footnotes or internal links, I am not going to try to recreate this functionality. I'm going to close this ticket, but if Atto becomes able to handle these, please reopen this ticket.

**Comment by monnardj** [comment] 2015-11-18 13:59
Hi, thanks for your comment. 
Actually, I was not expecting Atto to display the footnotes' text. But in the current situation, if you copy text which includes a footnote reference, the plugin pastes only the footnote text, and not the main text (see screenshot above), which is not very useful. It would be better if the plugin would just strip the footnote reference and display the main text.

**Comment by jinhofer** [comment] 2015-11-18 14:01
Ah, now that I can do! Thank you for following up on this. I have reopened this ticket and will work on this one.

**Comment by jinhofer** [comment] 2015-11-18 15:45
Looking into this, using version 2015111300, I am able to paste a footnote as well:
![image](https://cloud.githubusercontent.com/assets/8837519/11245562/fb2639f2-8dd8-11e5-981a-bdd6392c9aed.png)
Albeit with some minor formatting issues that I'm currently looking into. Are you able to reproduce this with the latest version?

**Comment by monnardj** [comment] 2015-11-18 16:02
With the latest version, it works now (just like your screenshot) in Firefox 42. But in Chrome 46 and Safari 9, I still only get the footnote text (all tested on a Mac, with Moodle 2.7.1).

**Comment by jinhofer** [comment] 2015-11-18 19:36
Alright, it made a very large difference being from a Mac. Try pulling from the master branch and testing that again, please.

As far as the HTML generation, there is some "MS garbage" that remains like font size and family, but that is because it changes depending on your personal settings. That makes a difference if you change font size, color, alignment, family, etc. There is a LOT being removed, such as pages of xml data, class names, id names, and mso specific styles.

**Comment by monnardj** [comment] 2015-11-19 07:14
Latest version works both in Safari and Chrome on Mac  :-)

**Comment by jinhofer** [comment] 2015-11-23 18:24
Awesome, thank you! I am working on a few other bugs specific to Microsoft Word now, but expect me to post an updated version of the plugin to Moodle soon.

**Comment by jinhofer** [comment] 2015-12-03 16:23
I have released a new version to Moodle! I'm going to close this ticket for now, but please keep me posted if you find any more issues.

**Closed by jinhofer** 2015-12-03 16:23 UTC
